name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore nuget
      run: nuget restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --framework netcoreapp3.1
    - name: Copy target data to staging
      run: mkdir staging && cp -R TS3AudioBot/* staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
